### ISSUE TITLE
Double rendering of astro component

### ISSUE THREAD

**Issue by simitch1** [analogjs/analog#79] opened 2022-09-04 22:26 UTC
### Please provide the environment you discovered this bug in.

I've recreated the issue in this repo:
https://github.com/simitch1/analog-astro-double-rendering-bug

### Which area/package is the issue in?

astro-angular

### Description

I saw that in some condition, the compilation or client hydration process creates multiple instance of the same component, one interactive and the other one not interactive.

I was able to recreate the bug by wrapping the angular component with a `<p>` tag.
I started looking for the bug but I haven't found it yet... 

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment] 2022-09-05 03:35
The client hydration fails because there is a property defined on the component that isn't an input. We'll need to add the same check that's on the server here https://github.com/analogjs/analog/blob/main/packages/astro-angular/src/server.ts#L52 to the client

https://github.com/analogjs/analog/blob/main/packages/astro-angular/src/client.ts#L22

The double render might be an upstream issue. I can reproduce it in a StackBlitz with React also using "astro-card" as the host element tag.

https://stackblitz.com/edit/github-lfap34?file=src%2Fpages%2Findex.astro,src%2Fcomponents%2FCounter.tsx&on=stackblitz

**Comment by brandonroberts** [comment] 2022-10-12 01:37
Fixed inputs with #81

**Closed by brandonroberts** 2022-10-12 01:37 UTC
Labels: bug
