### ISSUE TITLE
 `Nitro` throws an error when using `HttpClient ` with non-JSON `responseType`

### ISSUE THREAD

**Issue by lars0n** [analogjs/analog#1322] opened 2024-09-03 08:54 UTC
### Please provide the environment you discovered this bug in.

https://stackblitz.com/edit/github-sccmpf?file=src%2Fapp%2Fpages%2Findex.page.ts

### Which area/package is the issue in?

router

### Description

I've encountered an issue where `Nitro` throws an error during the server rendering step when using the `HttpClient` with the new Server Request Context feature, if the `responseType` is set to anything other than `json`. This error occurs when attempting to request data in formats such as `text`, `blob`, or `arraybuffer`.

### Please provide the exception or error you saw

```true
Response is not a string
```

### Other information

The issue originates from the `request-context.ts` file in the router package, where support for responseType needs to be added in Nitro's fetch client.

```js
    return from(
      global.$fetch
        .raw(fetchUrl, {
          method: req.method as any,
          params: requestUrl.searchParams,
          responseType: req.responseType, // add responseType support
          headers: req.headers.keys().reduce((hdrs, current) => {
            return {
              ...hdrs,
              [current]: req.headers.get(current),
            };
          }, {}),
        })
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment] 2024-09-05 20:08
Thanks @lars0n. The issue is assigned to you

**Closed** 2024-09-06 16:12 UTC
Labels: bug, accepting PRs
