### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'minimalContext')

### ISSUE THREAD

**Issue by monacodelisa** [analogjs/analog#1166] opened 2024-06-15 03:24 UTC
## Analog version 
v1.5.0

## Tested on:
3 windows machines
1 stackblitz 

https://stackblitz.com/github/analogjs/analog/tree/stackblitz/packages/create-analog/template-latest?file=vite.config.ts&preset=node

![image](https://github.com/analogjs/analog/assets/64324417/63bbb6ce-84b4-4b89-bdd4-ba2106758a01)

### Which area/package is the issue in?

create-analog

### Description

after running 
- `npm create analog@latest` 
- `npm i`
and when running `npm start` the analog app starts 
however this error message appears :

### Please provide the exception or error you saw

```true
TypeError: Cannot read properties of undefined (reading 'minimalContext')
TypeError: Cannot read properties of undefined (reading 'minimalContext')
```

### Other information

so far I know that this affects the styles:

- the elements are no longer centered
- the cool on hover box shadow on the Analog logo doesn't work 
and possibly more

I first encountered the error within the last 48h 
- 2 days ago I created a v1.5.0 Analog app without seeing this error message

As much as I would like to I could not submit a PR since I do not know where that 
`minimalContext` is, could not find it

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment] 2024-06-15 15:24
The issue is the Angular CLI is pinned to 5.2.11 and using ^5.0.0 installs the latest version of Vite which is 5.3.0. This causes two copies of Vite to be installed.

The fix has already landed on beta but you can update your package.json for Vite to `~5.2.11`

**Comment by monacodelisa** [comment] 2024-06-15 15:36
all paths lead to Vite 😅 ok, thank you so much @brandonroberts 
I will make the suggested adjustments 🙏

**Closed** 2024-06-15 16:54 UTC
Labels: bug

**Comment by brandonroberts** [comment] 2024-07-18 18:02
Landed a proper fix for this in https://github.com/analogjs/analog/pull/1214. It will go out with 1.6.2
