### ISSUE TITLE
Markdown content injection not working when repo / project name contains a period.

### ISSUE THREAD

**Issue by codephobia** [analogjs/analog#625] opened 2023-08-31 07:14 UTC
### Please provide the environment you discovered this bug in.

Windows, Node 18.14.0, NPM 9.4.2, Angular 16.2, @analogjs/content 0.2.0

### Which area/package is the issue in?

content

### Description

Following the walkthrough in Brandon's video here: https://www.youtube.com/watch?v=H4U6udLcM-Q. Name the project something like "domain.tld" and follow the remaining steps to setup markdown and the initial blog post.

### Please provide the exception or error you saw

```true
No error. The blog list and post redirect back to the main root of the application.
```

### Other information

I can confirm that creating another project without the period in project name resolved the issue.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment] 2023-09-05 02:22
Good catch. I've assigned it to you if you still want to work on a fix

**Comment by codephobia** [comment] 2023-09-07 00:59
> Good catch. I've assigned it to you if you still want to work on a fix

Yeah, I'll try to take a look at it this week / weekend.

**Comment by walter11235** [comment] 2023-09-28 05:53
I cannot reproduce the bug anymore, can someone check?

**Comment by michalgrzegorczyk-dev** [comment] 2023-09-29 18:48
Hi, I also have some problems with analog-markdown but it's not related to period in the repo name. I'm just getting 'Unknown html tag analog-markdown' even if everything is imported correctly and I don't see the content that is passed to this element. Anyone?

**Comment by brandonroberts** [comment] 2023-09-29 19:49
@michalgrzegorczyk-dev open a separate issue with a small reproduction and we'll take a look

**Closed** 2024-06-22 23:13 UTC
Labels: bug
