### ISSUE TITLE
PNPM Cannot find module @analogjs+vite-plugin-nitro api-middleware

### ISSUE THREAD

**Issue by AbdallahR99** [analogjs/analog#950] opened 2024-03-20 04:42 UTC
### Please provide the environment you discovered this bug in.

just installed the node modules of a new project using PNPM on windows 11

### Which area/package is the issue in?

vite-plugin-nitro

### Description

when I start the project I find an error that saying  `Cannot find module 'D:\D:\Work\ddapp\dd\node_modules\.pnpm\@analogjs+vite-plugin-nitro@1.0.1\node_modules\@analogjs\vite-plugin-nitro\src\lib\runtime\api-middleware' imported from D:\Work\ddapp\dd\dist\.nitro\prerender\index.mjs`

here there is ` `**D:\\D:\\** `Work\ddapp\dd..` which is a wrong path 

and in the `dist\.nitro\prerender\index.mjs` file I found this `import _mfXyn4 from '../../../../../../../../../../../D:/Work/ddapp/dd/node_modules/.pnpm/@analogjs+vite-plugin-nitro@1.0.1/node_modules/@analogjs/vite-plugin-nitro/src/lib/runtime/api-middleware';`

while the other imports r like this:

```
import process from 'node:process';globalThis._importMeta_={url:import.meta.url,env:process.env};import { defineEventHandler, handleCacheHeaders, splitCookiesString, isEvent, createEvent, fetchWithEvent, getRequestHeader, eventHandler, setHeaders, sendRedirect, proxyRequest, setResponseStatus, setResponseHeader, send, removeResponseHeader, createError, getResponseHeader, createApp, createRouter as createRouter$1, toNodeListener, lazyEventHandler } from 'file://D:/Work/ddapp/dd/node_modules/h3/dist/index.mjs';
import { createFetch as createFetch$1, Headers as Headers$1 } from 'file://D:/Work/ddapp/dd/node_modules/ofetch/dist/node.mjs';
import destr from 'file://D:/Work/ddapp/dd/node_modules/.pnpm/destr@2.0.3/node_modules/destr/dist/index.mjs';
import { createCall, createFetch } from 'file://D:/Work/ddapp/dd/node_modules/unenv/runtime/fetch/index.mjs';
import { createHooks } from 'file://D:/Work/ddapp/dd/node_modules/hookable/dist/index.mjs';
import { klona } from 'file://D:/Work/ddapp/dd/node_modules/klona/dist/index.mjs';
import { snakeCase } from 'file://D:/Work/ddapp/dd/node_modules/scule/dist/index.mjs';
import defu, { defuFn } from 'file://D:/Work/ddapp/dd/node_modules/defu/dist/defu.mjs';
import { hash } from 'file://D:/Work/ddapp/dd/node_modules/ohash/dist/index.mjs';
import { parseURL, withoutBase, joinURL, getQuery, withQuery, decodePath, withLeadingSlash, withoutTrailingSlash } from 'file://D:/Work/ddapp/dd/node_modules/ufo/dist/index.mjs';
import { createStorage, prefixStorage } from 'file://D:/Work/ddapp/dd/node_modules/unstorage/dist/index.mjs';
import unstorage_47drivers_47fs from 'file://D:/Work/ddapp/dd/node_modules/unstorage/drivers/fs.mjs';
import unstorage_47drivers_47fs_45lite from 'file://D:/Work/ddapp/dd/node_modules/unstorage/drivers/fs-lite.mjs';
import { toRouteMatcher, createRouter } from 'file://D:/Work/ddapp/dd/node_modules/radix3/dist/index.mjs';
import { promises } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'file://D:/Work/ddapp/dd/node_modules/pathe/dist/index.mjs';
```

angular-errors.log:

```
[error] Error: Cannot find module 'D:\D:\Work\ddapp\dd\node_modules\.pnpm\@analogjs+vite-plugin-nitro@1.0.1\node_modules\@analogjs\vite-plugin-nitro\src\lib\runtime\api-middleware' imported from D:\Work\ddapp\dd\dist\.nitro\prerender\index.mjs
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:324:11)
    at moduleResolve (node:internal/modules/esm/resolve:943:10)
    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)

```

### Please provide the exception or error you saw

```true
vite v5.0.0 building for production...
✓ 339 modules transformed.
dist/client/index.html                             1.73 kB │ gzip:  1.31 kB
dist/client/assets/index-CpflQZoc.css              5.69 kB │ gzip:  1.83 kB
dist/client/assets/pages.page-DD5gMGCp.js          0.69 kB │ gzip:  0.44 kB
dist/client/assets/(index).page-DL-wEyfW.js        1.30 kB │ gzip:  0.74 kB
dist/client/assets/analogjs-content-qHuW0Fe3.js  137.69 kB │ gzip: 44.61 kB
dist/client/assets/index-CsBA_PgR.js             269.48 kB │ gzip: 85.10 kB
Building SSR application...
✓ built in 18.42s
vite v5.0.0 building SSR bundle for production...
Prerendering static pages...
Building Server...
✓ 32 modules transformed.
dist/ssr/assets/pages.page-C23ZqRIW.js            1.47 kB
dist/ssr/assets/(index).page-DpFNitRd.js          2.48 kB
dist/ssr/assets/analogjs-content-Bd5qOT4v.js     19.03 kB
dist/ssr/assets/xhr2-CDOpgsGh.js                 36.45 kB
dist/ssr/main.server.js                       1,363.54 kB
✓ built in 31.89s
Prerendering static pages...


The '@analogjs/platform' server has been successfully built.
An unhandled exception occurred: Cannot find module 'D:\D:\Work\ddapp\dd\node_modules\.pnpm\@analogjs+vite-plugin-nitro@1.0.1\node_modules\@analogjs\vite-plugin-nitro\src\lib\runtime\api-middleware' imported from D:\Work\ddapp\dd\dist\.nitro\prerender\index.mjs
See "C:\Users\C_ABDA~1.ELR\AppData\Local\Temp\ng-VR0vtn\angular-errors.log" for further details.
```

### Other information

package.json:
```
{
  "name": "dd",
  "version": "0.0.0",
  "type": "module",
  "private": true,
  "engines": {
    "node": ">=18.13.0"
  },
  "scripts": {
    "dev": "ng serve",
    "ng": "ng",
    "start": "npm run dev",
    "build": "ng build",
    "watch": "ng build --watch",
    "test": "ng test"
  },
  "dependencies": {
    "@analogjs/content": "^1.0.0",
    "@analogjs/router": "^1.0.0",
    "@analogjs/vite-plugin-nitro": "^1.0.1",
    "@angular/animations": "^17.2.0",
    "@angular/common": "^17.2.0",
    "@angular/compiler": "^17.2.0",
    "@angular/core": "^17.2.0",
    "@angular/forms": "^17.2.0",
    "@angular/platform-browser": "^17.2.0",
    "@angular/platform-browser-dynamic": "^17.2.0",
    "@angular/platform-server": "^17.2.0",
    "@angular/router": "^17.2.0",
    "@nx/angular": "~18.0.0",
    "front-matter": "^4.0.2",
    "marked": "^5.0.2",
    "marked-gfm-heading-id": "^3.1.0",
    "marked-highlight": "^2.0.1",
    "mermaid": "^10.2.4",
    "prismjs": "^1.29.0",
    "rxjs": "~7.5.6",
    "tslib": "^2.4.0",
    "zone.js": "~0.14.0"
  },
  "devDependencies": {
    "@analogjs/platform": "^1.0.0",
    "@analogjs/vite-plugin-angular": "^1.0.0",
    "@angular/cli": "^17.2.0",
    "@angular/compiler-cli": "^17.2.0",
    "@nx/vite": "~18.0.0",
    "autoprefixer": "^10.4.14",
    "destr": "^2.0.3",
    "jsdom": "^22.1.0",
    "nx": "~18.0.0",
    "postcss": "^8.4.21",
    "tailwindcss": "^3.3.1",
    "typescript": "~5.3.0",
    "vite": "^5.0.0",
    "vitest": "^1.3.1"
  }
}
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment] 2024-03-20 18:43
Closing as duplicate of #945

**Closed by brandonroberts** 2024-03-20 18:43 UTC
Labels: bug
