### ISSUE TITLE
support for Angular v15

### ISSUE THREAD

**Issue by eng-dibo** [analogjs/analog#154] opened 2022-11-18 22:50 UTC
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

Angular v15 has been officially released but doesn't exist in the create-analog optoions

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment] 2022-11-18 23:56
Duplicate of   https://github.com/analogjs/analog/issues/116

**Closed** 2022-11-18 23:56 UTC
Labels: enhancement
