### ISSUE TITLE
[error] TypeError: Cannot read properties of undefined (reading 'executor')

### ISSUE THREAD

**Issue by c4mpos** [analogjs/analog#685] opened 2023-10-03 02:26 UTC
### Please provide the environment you discovered this bug in.

$ uname -a
Linux work 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Which area/package is the issue in?

create-analog

### Description

Steps to reproduce:

$ npm create analog@latest
$ cd analog-project
$ npm install
$ npm run start

### Please provide the exception or error you saw

```true
$ npm run start  

> analog-project@0.0.0 start
> npm run dev


> analog-project@0.0.0 dev
> ng serve

An unhandled exception occurred: Cannot read properties of undefined (reading 'executor')
See "/tmp/ng-238Xg8/angular-errors.log" for further details.

$ cat /tmp/ng-238Xg8/angular-errors.log                                    
[error] TypeError: Cannot read properties of undefined (reading 'executor')
    at readTargetOptions (/home/dev/proj/analog-site/analog-project/node_modules/@nx/devkit/src/executors/read-target-options.js:24:60)
    at getNxTargetOptions (/home/dev/proj/analog-site/analog-project/node_modules/@nx/vite/src/utils/options-utils.js:137:42)
    at viteDevServerExecutor (/home/dev/proj/analog-site/analog-project/node_modules/@nx/vite/src/executors/dev-server/dev-server.impl.js:24:69)
    at viteDevServerExecutor.next (<anonymous>)
    at recurse (/home/dev/proj/analog-site/analog-project/node_modules/@nx/devkit/src/utils/convert-nx-executor.js:61:26)
    at /home/dev/proj/analog-site/analog-project/node_modules/@nx/devkit/src/utils/convert-nx-executor.js:78:17
```

### Other information

**$ npm --version**
9.6.7

**$ node -v**
v18.17.1

**$ ng version**              

Angular CLI: 16.2.4
Node: 18.17.1
Package Manager: npm 9.6.7
OS: linux x64

Angular: 16.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.4
@angular-devkit/build-angular   16.2.4
@angular-devkit/core            16.2.4
@angular-devkit/schematics      16.2.4
@angular/cli                    16.2.4
@schematics/angular             16.2.4
rxjs                            7.5.7
typescript                      5.0.4
zone.js                         0.13.3

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment] 2023-10-03 12:04
Closing as a duplicate of https://github.com/analogjs/analog/issues/667

**Closed by brandonroberts** 2023-10-03 12:04 UTC
Labels: bug
