### ISSUE TITLE
Incremental static regeneration

### ISSUE THREAD

**Issue by lydemann** [analogjs/analog#871] opened 2024-01-26 22:32 UTC
### Which scope/s are relevant/related to the feature request?

platform

### Information

Incremental static regeneration, like we know it from Next.js, provides the speed of static generation while updating stale static pages and generating new static pages in the background. This would overcome one of the main disadvantages of SSG: having to redeploy.

### Describe any alternatives/workarounds you're currently using

An alternative workout is simply having to redeploy the front end.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by jdgamble555** [comment] 2024-02-29 00:18
ISR itself is nothing that great and can be achieve with simple headers. By ISR, you probably mean on-demand ISR. I thought I would chime in that ISR only runs on serverless and only on Vercel anyway. You can't get the same effect using Memory Key Value Stores or using Cache Purging on Edge computing, if that is important to you.

J

**Comment by brandonroberts** [comment] 2024-03-27 03:09
Closing as a duplicate of #127

**Closed by brandonroberts** 2024-03-27 03:09 UTC
Labels: enhancement
