### ISSUE TITLE
support for Tailwind (flowbite) lib (ERROR ReferenceError: document is not defined)

### ISSUE THREAD

**Issue by PiotrMistu** [analogjs/analog#751] opened 2023-11-12 17:03 UTC
### Please provide the environment you discovered this bug in.

Like i the title, i have a problem after installation of flowbite i have no access to document, what is understandable and i think solved for Nuxt or Next js, and i think this is common problem can someone help with it?
ERROR ReferenceError: document is not defined
    at initAccordions (/xxx/xxx/node_modules/flowbite/lib/cjs/components/accordion/index.js:145:5)

for now i just set SSR to off analog({ssr: false}), but it is workaround

**Comment by goetzrobin** [comment] 2023-11-12 18:02
So as you've noticed the issue is that on the server side the document object is not available. That is the reason why it is recommended to use Angular's dependency injection mechanism to access it.

Angular does some DOM emulation during SSR, which we added the import for in this commit: https://github.com/analogjs/analog/commit/f45a4df3fa71cf1df9737a323b16762602e6ccdc

However, I am not 100% sure if this would fix your issue. 

If this is a new project installed with Nx and already has that line in your main.server.ts then as far as I know the only way to fix it would be for Flowbite to avoid this direct access to the document object...

If this change is not already reflected in your project it might make it work!

Please let me know if this helps!

**Comment by PiotrMistu** [comment] 2023-11-12 19:14
This is a very new project created today i am working on tech stack :) for it. 
We want to try this SSR as a time but it is one a first case, vite is the most important for me now ( as tech solution).

But, if u detect this issue it is a chance that it will work later ?

**Comment by goetzrobin** [comment] 2023-12-18 09:03
@PiotrMistu I wanted to follow up on this and see if you got this to work. I am going to close this issue as if the issue persists this is something that needs to be addressed on the Flowbite side.

**Closed by goetzrobin** 2023-12-18 09:03 UTC
Labels: bug

**Comment by dev-garcia** [comment] 2024-01-07 17:45
The problem persists, I have the same problem, is there any forecast to be fixed? because we'll have to look for another lib to use with SSR

**Comment by goetzrobin** [comment] 2024-01-07 21:50
Unfortunately, this is an issue with the flowbite library and not something the AnalogJs team can fix. You’d need to open an issue in their repository so they can ensure SSR support and not directly relying on native browser APIs like window, etc. maybe you can workaround the issue and use the new @defer syntax to only load the component in the browser if the component in question is not necessarily needed to build the page on the server…

**Comment by brandonroberts** [comment] 2024-01-08 02:16
I agree with @goetzrobin. If you can put together a GitHub repo with an example, maybe we can give you a recommendation, but if the library is only meant to be used in the browser, then you'll have to add some checks to make sure its only loaded there.

**Comment by MatthewNicastro** [comment] 2024-05-01 03:47
Hey all very new to angular (however I have a very strong background in React and Vue). I did some digging around the flowbite errors and found this (issue)[https://github.com/themesberg/flowbite/issues/769]. I think this might be the fix to the problem (I just realized that @dev-garcia posted the initial issue so linking here for others who stumble across this issue like I did).

**Comment by brandonroberts** [comment] 2024-05-01 13:02
Cool, thanks @MatthewNicastro
