### ISSUE TITLE
Can't run tests with newest update (1.9.2)

### ISSUE THREAD

**Issue by jahusa02** [analogjs/analog#1436] opened 2024-11-06 05:27 UTC
### Please provide the environment you discovered this bug in.

We use nx with analog vitest

### Which area/package is the issue in?

vitest-angular

### Description

Everytime I run the tests I get the error:

```
ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/reneachtelik/workspace/fhp-bike/node_modules/.pnpm/@analogjs+vitest-angular@1.9.2_@analogjs+vite-plugin-angular@1.9.2_@angular-devkit+build-angu_tfhrvuljhjniigrh7pmftb3w5m/node_modules/@analogjs/vitest-angular/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
 ❯ ../../../node_modules/.pnpm/@analogjs+vitest-angular@1.9.2_@analogjs+vite-plugin-angular@1.9.2_@angular-devkit+build-angu_tfhrvuljhjniigrh7pmftb3w5m/node_modules/@analogjs/vitest-angular/setup-zone.js:2:23
      1| "use strict";
      2| Object.defineProperty(exports, "__esModule", { value: true });
       |                       ^
      3| require("zone.js");
      4| require("zone.js/plugins/sync-test");
 ❯ src/test-setup.ts:1:1
```

project is esm only.

### Please provide the exception or error you saw

```true
ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/reneachtelik/workspace/fhp-bike/node_modules/.pnpm/@analogjs+vitest-angular@1.9.2_@analogjs+vite-plugin-angular@1.9.2_@angular-devkit+build-angu_tfhrvuljhjniigrh7pmftb3w5m/node_modules/@analogjs/vitest-angular/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
 ❯ ../../../node_modules/.pnpm/@analogjs+vitest-angular@1.9.2_@analogjs+vite-plugin-angular@1.9.2_@angular-devkit+build-angu_tfhrvuljhjniigrh7pmftb3w5m/node_modules/@analogjs/vitest-angular/setup-zone.js:2:23
      1| "use strict";
      2| Object.defineProperty(exports, "__esModule", { value: true });
       |                       ^
      3| require("zone.js");
      4| require("zone.js/plugins/sync-test");
 ❯ src/test-setup.ts:1:1
```

### Other information

Happens only with the newest update

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment] 2024-11-06 13:48
Is this Nx 20?

**Comment by brandonroberts** [comment] 2024-11-06 14:05
Make sure your `vite.config.ts` is named `vite.config.mts` if its just for testing which will force ESM.

**Comment by brandonroberts** [comment] 2024-11-07 16:02
Can you provide a reproduction? I could see this happening if it's running in ESM-only mode, but Nx doesn't run as ESM. What version of Vitest?

**Comment by fabian-paus** [comment] 2024-11-08 09:00
Hi, we encountered a very similar problem (same error message). For us, it is connected to the pool = "threads" option that seems to change how module loading works (or doesn't work).

Here is a complete reproduction guide: https://github.com/fabian-paus/angular-vitest-bug

The error can simple be reproduced by:
- Setting up an analogjs project: npm create analog@latest
- Then changing the test config to pool = "threads" (or "forks")

The problem can be "solved" by editing `@analogjs\vitest-angular\package.json` to "type": "commonjs".

I am a novice on this whole CommonJS / ESM debacle. But I tried looking into @analogjs\vitest-angular. It seems to contain CommonJS code (require syntax), but is marked as "type": "module", which indicates ESM syntax (import, export).

It seems that with pool = "vmThreads" vitest somehow ignores this inconsistency.

Changing the config from .ts to .mts did not change anything.

The error is reproducible on any system and version that I tried:
- Windows and Linux
- Node 22.11 and 20.18
- Vitest version 1.6 and 2.1.4

**Closed** 2024-11-08 14:53 UTC
Labels: bug

**Comment by brandonroberts** [comment] 2024-11-08 14:59
The fix has landed in Analog `1.9.3-beta.1` for testing

**Comment by Yberion** [comment] 2024-11-08 17:49
I had the same problem and it was caused by https://github.com/analogjs/analog/pull/1434, downgrading to `v1.9.2-beta.3` and all was working as before. It's curious that it would be affected by `"type": "module"`.

My Vitest file are already `vite.config.mts`.

**Comment by brandonroberts** [comment] 2024-11-08 19:28
@Yberion interesting, I wouldn't have expected that. So everything is back working with the latest beta?

**Comment by brandonroberts** [comment] 2024-11-08 19:34
@jahusa02 ok cool

**Comment by Yberion** [comment] 2024-11-08 20:17
> @Yberion interesting, I wouldn't have expected that. So everything is back working with the latest beta?

Yeah it is now working with the last beta.

But still confused about why adding `nx` to `optimizeDependencies.exclude ` would suddently cause this problem. Perhaps esbuild was optimizing the code and translating it somehow to ESM compatible code.

**Comment by brandonroberts** [comment] 2024-11-12 14:12
> > @Yberion interesting, I wouldn't have expected that. So everything is back working with the latest beta?
> 
> Yeah it is now working with the last beta.
> 
> But still confused about why adding `nx` to `optimizeDependencies.exclude ` would suddently cause this problem. Perhaps esbuild was optimizing the code and translating it somehow to ESM compatible code.

Probably so. `nx` is still CommonJS right now, so it would try to optimize it along with its dependencies, which could lead to a bit of "over optimizing"

**Comment by brandonroberts** [comment] 2024-11-12 15:21
`Analog 1.9.3` is released with the fix
